let offSetX=50;let offSetY=25;function setup(){let height=document.getElementById('theWidth').offsetHeight;let width=document.getElementById('theWidth').offsetWidth;let myCanvas=createCanvas(width,400);myCanvas.parent("idnameofdiv");}
function draw(){background(250);let vtr=createVector(100,400,50);let elSize=25;let yHeight=height+elSize;let cycleCount=app.cycleCount;let stationIn=createVector(vtr.x+width/36-20,yHeight,elSize);let station1=createVector(vtr.x+width/6-20,yHeight,elSize);let station2=createVector(vtr.x+width/3-20,yHeight,elSize);let station3=createVector(vtr.x+width/2-20,yHeight,elSize);let station4=createVector(vtr.x+width/1.5-20,yHeight,elSize);let station5=createVector(vtr.x+5*width/6-20,yHeight,elSize);let stationOut=createVector(vtr.x+width-160,yHeight,elSize);let stationVList=[station1,station2,station3,station4,station5];let divFour=createVector(0,15,0);let modFour=createVector(0,35,0);for(i=1;i<6;i++){line(5+width/6.55,100*i,width-72,100*i)};drawGame()
function drawGame(){line(stationOut.x-10,0,stationOut.x-10,400)
line(stationOut.x,0,stationOut.x,400)
for(i=0;i<5;i++){line(stationVList[i].x-80-(i*11),0,stationVList[i].x-80-(i*11),400)
line(stationVList[i].x-90-(i*11),0,stationVList[i].x-90-(i*11),400)}};if(cycleCount==1){app.cycle()}
if(app.beadsOutput>99){app.beadsOutput=0}
initedBeads=initBeads(stationIn,app.beadNew,0,0);initBeads(stationOut.add(50,0,0),app.beadsOutput,0,0);initBeads(station1,parseInt(app.station1.out),0,0);initBeads(station2,parseInt(app.station2.out),0,0);initBeads(station3,parseInt(app.station3.out),0,0);initBeads(station4,parseInt(app.station4.out),0,0);initBeads(station5,parseInt(app.station5.out),0,0);initBeads(station1,parseInt(app.station1.wip),offSetX,offSetY);initBeads(station2,parseInt(app.station2.wip),offSetX,offSetY);initBeads(station3,parseInt(app.station3.wip),offSetX,offSetY);initBeads(station4,parseInt(app.station4.wip),offSetX,offSetY);initBeads(station5,parseInt(app.station5.wip),offSetX,offSetY);function initBeads(stationVector,amount,xOffSet,yOffSet){let beadList=[];let col=color(2,204,14);fill(col);if(amount>=4){for(j=0;j<(amount-(amount%4))/4;j++){stationVector.add(divFour)
for(i=0;i<4;i++){x=parseInt(stationVector.x-i*(elSize/2)-parseInt(xOffSet));y=parseInt(stationVector.y-400+i*(elSize/16)+parseInt(yOffSet));ellipse(x,y,stationVector.z)}}
stationVector.add(modFour)
for(h=0;h<amount%4;h++){x=parseInt(stationVector.x-h*(elSize/2)-parseInt(xOffSet));y=parseInt(stationVector.y-400+h*(elSize/16)+parseInt(yOffSet));ellipse(x,y,stationVector.z)}}
if(amount<4){stationVector.add(modFour)
for(k=0;k<amount;k++){x=parseInt(stationVector.x-k*(elSize/2)-parseInt(xOffSet));y=parseInt(stationVector.y-400+k*(elSize/16)+parseInt(yOffSet));ellipse(x,y,stationVector.z)}}};};